### ISSUE TITLE
1.0.6 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Jgta4444** [phantamanta44/libnine#2]
https://gist.github.com/Jgta4444/4dc469993f5e3c3489e9e6e2c728231d
Crash on load

**Comment by phantamanta44** [comment]
could you try downgrading forge to 14.23.5.2768?

**Comment by Jgta4444** [comment]
> 
> 
> could you try downgrading forge to 14.23.5.2768?

Unfortunately many mods in my modpack have 2836 as hard dependency

**Comment by phantamanta44** [comment]
well, that's annoying. i'll see what i can do

**Comment by phantamanta44** [comment]
give it a shot with [libnine 1.1.0](https://www.curseforge.com/minecraft/mc-mods/libnine/files/2743076) and [lazy-ae2 1.1.0](https://www.curseforge.com/minecraft/mc-mods/lazy-ae2/files/2743077)

**Comment by AndreiTS** [comment]
[crash-2019-07-17_14.35.33-client.txt](https://github.com/phantamanta44/libnine/files/3403123/crash-2019-07-17_14.35.33-client.txt)

Using libnine 1.1 and lazy-ae2 1.1

**Comment by phantamanta44** [comment]
i think i might have uploaded the wrong jarfile lol
[try this one](https://www.curseforge.com/minecraft/mc-mods/libnine/files/2743094)

**Comment by AndreiTS** [comment]
It worked with this version

**Comment by Jgta4444** [comment]
Yep, it loads fine
